---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busapp
      tier: frontend
  template:
    metadata:
      labels:
        app: busapp
        tier: frontend
    spec:
      containers:
        - name: app
          image: venkatramanan83/base:latest
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: busapp
  namespace: develop
spec:
  selector:
    app: busapp
    tier: frontend

  ports:
    - port: 80
      targetPort: 8001
  type: LoadBalancer
